version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 16
    commands:
      - npm install -g yarn
      - yarn install

  pre_build:
    commands:
      # Optionally, you can run any pre-build commands here

  build:
    commands:
      - yarn build

artifacts:
  files:
    - '**/*'
  base-directory: 'dist' # Adjust this based on your Vite output directory
